# Generated by Django 3.2.5 on 2021-07-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210712_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcategory'),
        ),
    ]
