# Generated by Django 3.2.5 on 2021-08-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
